# Generated by Django 5.1.5 on 2025-02-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_images_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=False, unique=True),
            preserve_default=False,
        ),
    ]
