# Generated by Django 5.1.5 on 2025-02-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=100, null=True)),
                ('care_difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('DIFFICULT', 'Difficult')], max_length=20)),
                ('sunlight_requirements', models.CharField(choices=[('FULL_SUN', 'Full Sun'), ('PARTIAL_SUN', 'Partial Sun'), ('SHADE', 'Shade')], max_length=50)),
                ('water_frequency', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='store.category')),
                ('tags', models.ManyToManyField(blank=True, to='store.tag')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='plant',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='store.plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='plant',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='store.plant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'plant')},
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
