# Generated by Django 5.1.5 on 2025-03-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_category_id_alter_plant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='care_difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('DIFFICULT', 'Difficult')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight_requirements',
            field=models.CharField(blank=True, choices=[('FULL_SUN', 'Full Sun'), ('PARTIAL_SUN', 'Partial Sun'), ('SHADE', 'Shade')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='water_frequency',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], max_length=50, null=True),
        ),
    ]
